- route:
    id: doctor-profile-list-route
    from:
      uri: direct:doctor-profile-list
      steps:
        - process:
            ref: doctorProfileListProcessor
        - marshal:
            json: { }

- route:
    id: doctor-profile-count-route
    from:
      uri: direct:doctor-profile-count
      steps:
        - process:
            ref: doctorProfileCountProcessor
        - marshal:
            json: { }

- route:
    id: doctor-profile-get-route
    from:
      uri: direct:doctor-profile-get
      steps:
        - process:
            ref: doctorProfileGetProcessor
        - marshal:
            json: { }

- route:
    id: doctor-profile-create-route
    from:
      uri: direct:doctor-profile-create
      steps:
        - setHeader:
            name: X-DTO-Class
            constant: com.camel.clinic.dto.doctorProfile.CreateDoctorProfileDto
        - process:
            ref: requestDeserializerProcessor
        - process:
            ref: validationProcessor
        - process:
            ref: doctorProfileCreateProcessor
        - marshal:
            json: { }

- route:
    id: doctor-profile-update-route
    from:
      uri: direct:doctor-profile-update
      steps:
        - setHeader:
            name: X-DTO-Class
            constant: com.camel.clinic.dto.doctorProfile.UpdateDoctorProfileDto
        - process:
            ref: requestDeserializerProcessor
        - process:
            ref: validationProcessor
        - process:
            ref: doctorProfileUpdateProcessor
        - marshal:
            json: { }

- route:
    id: doctor-profile-restore-route
    from:
      uri: direct:doctor-profile-restore
      steps:
        - process:
            ref: doctorProfileRestoreProcessor
        - marshal:
            json: { }

- route:
    id: doctor-profile-delete-route
    from:
      uri: direct:doctor-profile-delete
      steps:
        - process:
            ref: doctorProfileDeleteProcessor
        - marshal:
            json: { }