- onException:
    exception:
      - java.lang.Exception
    handled:
      constant: true
    steps:
      - process:
          ref: exceptionProcessor
      - marshal:
          json: { }

- route:
    id: staff-invoice-list-route
    from:
      uri: direct:staff-invoice-list
      steps:
        - process:
            ref: invoiceListProcessor
        - marshal:
            json: { }

- route:
    id: staff-invoice-count-route
    from:
      uri: direct:staff-invoice-count
      steps:
        - process:
            ref: invoiceCountProcessor
        - marshal:
            json: { }

- route:
    id: staff-invoice-get-route
    from:
      uri: direct:staff-invoice-get
      steps:
        - process:
            ref: invoiceGetProcessor
        - marshal:
            json: { }

- route:
    id: staff-invoice-create-route
    from:
      uri: direct:staff-invoice-create
      steps:
        - setHeader:
            name: X-DTO-Class
            constant: com.camel.clinic.dto.invoice.CreateInvoiceDto
        - process:
            ref: requestDeserializerProcessor
        - process:
            ref: validationProcessor
        - process:
            ref: invoiceCreateProcessor
        - marshal:
            json: { }

- route:
    id: staff-invoice-update-route
    from:
      uri: direct:staff-invoice-update
      steps:
        - setHeader:
            name: X-DTO-Class
            constant: com.camel.clinic.dto.invoice.UpdateInvoiceDto
        - process:
            ref: requestDeserializerProcessor
        - process:
            ref: validationProcessor
        - process:
            ref: invoiceUpdateProcessor
        - marshal:
            json: { }

- route:
    id: staff-invoice-restore-route
    from:
      uri: direct:staff-invoice-restore
      steps:
        - process:
            ref: invoiceRestoreProcessor
        - marshal:
            json: { }

- route:
    id: staff-invoice-delete-route
    from:
      uri: direct:staff-invoice-delete
      steps:
        - process:
            ref: invoiceDeleteProcessor
        - marshal:
            json: { }

- route:
    id: patient-invoice-list-route
    from:
      uri: direct:patient-invoice-list
      steps:
        - process:
            ref: invoiceListProcessor
        - marshal:
            json: { }

- route:
    id: patient-invoice-count-route
    from:
      uri: direct:patient-invoice-count
      steps:
        - process:
            ref: invoiceCountProcessor
        - marshal:
            json: { }

- route:
    id: patient-invoice-get-route
    from:
      uri: direct:patient-invoice-get
      steps:
        - process:
            ref: invoiceGetProcessor
        - marshal:
            json: { }

- route:
    id: patient-invoice-update-route
    from:
      uri: direct:patient-invoice-update
      steps:
        - setHeader:
            name: X-DTO-Class
            constant: com.camel.clinic.dto.invoice.UpdateInvoiceDto
        - process:
            ref: requestDeserializerProcessor
        - process:
            ref: validationProcessor
        - process:
            ref: invoiceUpdateProcessor
        - marshal:
            json: { }