- onException:
    exception:
      - java.lang.Exception
    handled:
      constant: true
    steps:
      - process:
          ref: exceptionProcessor
      - marshal:
          json: { }

- route:
    id: auth-register-route
    from:
      uri: direct:auth-register
      steps:
        - setHeader:
            name: X-DTO-Class
            constant: com.camel.clinic.dto.auth.RegisterRequestDTO
        - process:
            ref: requestDeserializerProcessor
        - process:
            ref: validationProcessor
        - process:
            ref: registerAuthProcessor
        - marshal:
            json: { }

- route:
    id: auth-login-route
    from:
      uri: direct:auth-login
      steps:
        - setHeader:
            name: X-DTO-Class
            constant: com.camel.clinic.dto.auth.LoginRequestDTO
        - process:
            ref: requestDeserializerProcessor
        - process:
            ref: validationProcessor
        - process:
            ref: loginAuthProcessor
        - marshal:
            json: { }

- route:
    id: auth-refresh-route
    from:
      uri: direct:auth-refresh
      steps:
        - setHeader:
            name: X-DTO-Class
            constant: com.camel.clinic.dto.auth.RefreshRequestDTO
        - process:
            ref: requestDeserializerProcessor
        - process:
            ref: validationProcessor
        - process:
            ref: refreshAuthProcessor
        - marshal:
            json: { }

- route:
    id: auth-logout-route
    from:
      uri: direct:auth-logout
      steps:
        - setHeader:
            name: X-DTO-Class
            constant: com.camel.clinic.dto.auth.LogoutRequestDTO
        - process:
            ref: requestDeserializerProcessor
        - process:
            ref: validationProcessor
        - process:
            ref: logoutAuthProcessor
        - marshal:
            json: { }

- route:
    id: auth-forgot-password-route
    from:
      uri: direct:auth-forgot-password
      steps:
        - setHeader:
            name: X-DTO-Class
            constant: com.camel.clinic.dto.auth.ForgotPasswordRequestDTO
        - process:
            ref: requestDeserializerProcessor
        - process:
            ref: validationProcessor
        - process:
            ref: forgotPasswordAuthProcessor
        - marshal:
            json: { }

- route:
    id: auth-verify-otp-route
    from:
      uri: direct:auth-verify-otp
      steps:
        - setHeader:
            name: X-DTO-Class
            constant: com.camel.clinic.dto.auth.VerifyOtpRequestDTO
        - process:
            ref: requestDeserializerProcessor
        - process:
            ref: validationProcessor
        - process:
            ref: verifyOtpAuthProcessor
        - marshal:
            json: { }

- route:
    id: auth-reset-password-route
    from:
      uri: direct:auth-reset-password
      steps:
        - setHeader:
            name: X-DTO-Class
            constant: com.camel.clinic.dto.auth.ResetPasswordRequestDTO
        - process:
            ref: requestDeserializerProcessor
        - process:
            ref: validationProcessor
        - process:
            ref: resetPasswordAuthProcessor
        - marshal:
            json: { }

- route:
    id: auth-get-profile-route
    from:
      uri: direct:auth-get-profile
      steps:
        - process:
            ref: getUserProfile
        - marshal:
            json: { }

- route:
    id: auth-change-password-route
    from:
      uri: direct:auth-change-password
      steps:
        - setHeader:
            name: X-DTO-Class
            constant: com.camel.clinic.dto.auth.ChangePasswordRequestDTO
        - process:
            ref: requestDeserializerProcessor
        - process:
            ref: validationProcessor
        - process:
            ref: changePasswordAuthProcessor
        - marshal:
            json: { }

- route:
    id: specialty-list-route
    from:
      uri: direct:specialty-list
      steps:
        - process:
            ref: specialtyListProcessor
        - marshal:
            json: { }

- route:
    id: specialty-count-route
    from:
      uri: direct:specialty-count
      steps:
        - process:
            ref: specialtyCountProcessor
        - marshal:
            json: { }

- route:
    id: specialty-get-route
    from:
      uri: direct:specialty-get
      steps:
        - process:
            ref: specialtyGetProcessor
        - marshal:
            json: { }

- route:
    id: specialty-create-route
    from:
      uri: direct:specialty-create
      steps:
        - setHeader:
            name: X-DTO-Class
            constant: com.camel.clinic.dto.specialty.CreateSpecialtyDto
        - process:
            ref: requestDeserializerProcessor
        - process:
            ref: validationProcessor
        - process:
            ref: specialtyCreateProcessor
        - marshal:
            json: { }

- route:
    id: specialty-update-route
    from:
      uri: direct:specialty-update
      steps:
        - setHeader:
            name: X-DTO-Class
            constant: com.camel.clinic.dto.specialty.UpdateSpecialtyDto
        - process:
            ref: requestDeserializerProcessor
        - process:
            ref: validationProcessor
        - process:
            ref: specialtyUpdateProcessor
        - marshal:
            json: { }

- route:
    id: specialty-delete-route
    from:
      uri: direct:specialty-delete
      steps:
        - process:
            ref: specialtyDeleteProcessor
        - marshal:
            json: { }

- route:
    id: service-list-route
    from:
      uri: direct:service-list
      steps:
        - process:
            ref: serviceListProcessor
        - marshal:
            json: { }

- route:
    id: service-count-route
    from:
      uri: direct:service-count
      steps:
        - process:
            ref: serviceCountProcessor
        - marshal:
            json: { }

- route:
    id: service-get-route
    from:
      uri: direct:service-get
      steps:
        - process:
            ref: serviceGetProcessor
        - marshal:
            json: { }

- route:
    id: service-create-route
    from:
      uri: direct:service-create
      steps:
        - setHeader:
            name: X-DTO-Class
            constant: com.camel.clinic.dto.services.CreateServiceDto
        - process:
            ref: requestDeserializerProcessor
        - process:
            ref: validationProcessor
        - process:
            ref: serviceCreateProcessor
        - marshal:
            json: { }

- route:
    id: service-update-route
    from:
      uri: direct:service-update
      steps:
        - setHeader:
            name: X-DTO-Class
            constant: com.camel.clinic.dto.services.UpdateServiceDto
        - process:
            ref: requestDeserializerProcessor
        - process:
            ref: validationProcessor
        - process:
            ref: serviceUpdateProcessor
        - marshal:
            json: { }

- route:
    id: service-delete-route
    from:
      uri: direct:service-delete
      steps:
        - process:
            ref: serviceDeleteProcessor
        - marshal:
            json: { }